CREATE DATABASE `immigrant`;

CREATE TABLE `immigrant` (
	`Id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PassportNumber` CHAR(255) NOT NULL,
	`HashAddress` CHAR(255) NOT NULL,
	`CreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`ModifiedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
